Clam 1293 rust cdiff
jhumlick/clamav pull request #1
Opened 2021-07-08 20:48 UTC by jhumlick

There is currently a bug during exchange. The expected string doesn't match what it gets, and it will assert there.

This review is intended more for suggestions of how to refactor and rewrite this code rather than to get the code that is contained in the review checked in. I know that I am weak in rust and will need to rewrite large portions of this code to follow the Rust paradigm.

I did not get the chance to rewrite the gross nested if block yet. Micah proposed an alternative to that, but feel free to make suggestions. You will know it when you see it.

2021-07-22 22:25 UTC, micahsnyder commented on CMakeLists.txt
> +    add_subdirectory( common_rust )
This isn't so much an issue as it is an idea.  I'm thinking it may be simplest if we put cdiff/rdiff into libclamav (`libclamav_rust/cdiff`). 
I mostly started thinking of this when I was thinking about how to integrate clamav's logging with new rust code.
If it's all within libclamav_rust, then we only need 1 rust logger implementation that wraps the cli_dbgmsg/cli_infomsg/cli_warnmsg/cli_errmsg functions and we don't need a second one that wraps the logg() function.
That said, we still may one a second one eventually if we start replacing programs like clamd, clamscan, and sigtool with versions written in Rust.
Something to think about.

2021-07-22 22:25 UTC, micahsnyder commented on common_rust/Makefile.am
> +#
Since you rebased your work to a newer version where the Autotools build is gone -- this file can be removed.

2021-07-22 22:25 UTC, micahsnyder commented on common_rust/rdiff/Cargo.toml
> +flate2 = "1.0.3"
Github is upset about a missing newline at the end.

2021-07-22 22:51 UTC, micahsnyder commented on common_rust/rdiff/rdiff.rs
> +fn get_hash<'a>(file: &mut File, len: usize) -> [u8; 32] {
Looks like you can remove `<'a>` as you're not using this lifetime anywhere.  Same for:
```rust
fn read_size<'a>(...)
fn read_dsig<'a>(...)
fn cmd_close<'a>(...)
fn process_lines<'a, T>(...)
fn cmd_close<'a>(...)
```

2021-07-23 18:11 UTC, micahsnyder requested changes

2021-07-23 18:11 UTC, micahsnyder commented on common_rust/rdiff/rdiff.rs
> +// Return two strings
I like the comments. The rest of the file could use more like this.
But also can you please add an extra `/` to follow the outer comment style for Rust? 
https://learning-rust.github.io/docs/a5.comments_and_documenting_the_code.html

Any additional improvements you can do to follow Rust documentation idioms would be great.

2021-07-23 18:11 UTC, micahsnyder commented on common_rust/rdiff/rdiff.rs
> +        //string2.trim().to_owned();
If this isn't needed, please remove it.

2021-07-23 18:11 UTC, micahsnyder commented on common_rust/rdiff/rdiff.rs
> +fn split_string(line: String) -> Result<(String, String), &'static str> {
When we were discussing this function back on 5/14, I shared some tests for it. I think it would be good to include these  tests (at the bottom of this file).  

```rust
#[cfg(test)]
mod tests {
    // Note this useful idiom: importing names from outer (for mod tests) scope.
    use super::*;

    #[test]
    fn hello_world() {
        let x = split_string(String::from("hello world")).unwrap();
        assert_eq!(x.0, "hello");
        assert_eq!(x.1, "world");
    }

    #[test]
    fn hello_my_friend() {
        let x = split_string(String::from("hello my friend")).unwrap();
        assert_eq!(x.0, "hello");
        assert_eq!(x.1, "my friend");
    }
}
```

I would also like it if you would create more tests on your own to demonstrate correct behavior for the features.

2021-07-23 18:11 UTC, micahsnyder commented on common_rust/rdiff/rdiff.rs
> +        "MOVE" => {
From our conversation on 5/26 on how to refactor to get rid of this `if() { if() { if() {...` code smell:

I came up with an idea for defining operations as `struct`s and implementing an `execute()` function for each. 
Here is my example library to test the idea:

```rust
use thiserror::Error;

/// CdiffError enumerates all possible errors returned by this library.
#[derive(Error, Debug)]
pub enum CdiffError {
    #[error("Unexpected end of line")]
    NoMoreDataError,

    #[error("Failed to parse string as a number")]
    ParseIntError(#[from] std::num::ParseIntError),

    /// Represents all other cases of `std::io::Error`.
    #[error(transparent)]
    IOError(#[from] std::io::Error),
}

#[derive(Debug)]
pub struct MoveOp<'a> {
    src: &'a str,
    dst: &'a str,
    start_line_no:i32,
    start_line: &'a str,
    end_line_no: i32,
    end_line: &'a str,
}

impl <'a> MoveOp<'a> {
    pub fn new(data: &'a str) -> Result<Self, CdiffError> {
        // Extract src db, dst db, start line no, start line, end line no, end line
        let mut iter = data.split_whitespace();

        Ok(MoveOp {
            src: iter.next().ok_or(CdiffError::NoMoreDataError)?,
            dst: iter.next().ok_or(CdiffError::NoMoreDataError)?,
            start_line_no: iter.next().ok_or(CdiffError::NoMoreDataError)?.parse::<i32>()?,
            start_line: iter.next().ok_or(CdiffError::NoMoreDataError)?,
            end_line_no: iter.next().ok_or(CdiffError::NoMoreDataError)?.parse::<i32>()?,
            end_line: iter.next().ok_or(CdiffError::NoMoreDataError)?,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_move_works() {
        eprintln!("MOVE was called!");

        let move_op = MoveOp::new("a b 1 hello 2 world").expect("Should've worked!");

        println!("{:?}", move_op);

        assert_eq!(move_op.src, "a");
        assert_eq!(move_op.dst, "b");
        assert_eq!(move_op.start_line_no, 1);
        assert_eq!(move_op.start_line, "hello");
        assert_eq!(move_op.end_line_no, 2);
        assert_eq!(move_op.end_line, "world");
    }

    #[test]
    fn parse_move_works_2() {
        eprintln!("MOVE was called!");

        MoveOp::new("a b NOTANUMBER hello 2 world").expect_err("Should've failed!");
    }
}
```
> _Note_: I brought in the thiserror dependency which makes error handling in a library a whole lot easier.

You can test this with `cargo test -- --nocapture`:
```sh
parse_move on  master [?] is 📦 v0.1.0 via 🦀 v1.52.1
❯ cargo test -- --nocapture
   Compiling parse_move v0.1.0 (/home/micasnyd/workspace/parse_move)
    Finished test [unoptimized + debuginfo] target(s) in 0.75s
     Running unittests (target/debug/deps/parse_move-4645e75af48de775)

running 2 tests
MOVE was called!
MoveOp { src: "a", dst: "b", start_line_no: 1, start_line: "hello", end_line_no: 2, end_line: "world" }
MOVE was called!
test tests::parse_move_works ... ok
test tests::parse_move_works_2 ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests parse_move

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

2021-07-23 18:15 UTC, micahsnyder commented
Can you share instructions for how to test your work?  (And once it has unit tests, on how to run the unit tests)

2021-07-23 18:27 UTC, micahsnyder commented on common_rust/CMakeLists.txt
> +add_library(ClamAV::rdiff ALIAS rdiff)
Once you have unit tests for rdiff, you can add them into the clamav test suite by adding this:
```cmake
add_rust_test( NAME rdiff WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/rdiff" )
```

2021-07-29 18:23 UTC, micahsnyder commented
BTW, Scott said he wants to wait for you to refactor based on my review before adding his own.

2021-08-20 00:13 UTC, jhumlick commented on CMakeLists.txt
> +    add_subdirectory( common_rust )
This should be resolved in my latest commit. Let's discuss this tomorrow and see if further changes need to be made.

2021-08-25 01:02 UTC, micahsnyder commented on libfreshclam/CMakeLists.txt
> +        ClamAV::cdiff
I'm not sure if we want to do it this way, or have the cdiff bit linked into a either a libclamav_rust module or libclamav and then brought in that way?  I dunno.  Let's do it this way for now, and we can always change things later as we accumulate more Rust modules.

2021-08-25 01:02 UTC, micahsnyder commented on sigtool/sigtool.c
> +// common rust
this could just go under the `// libclamav` section or we could add a `// libclamav rust` section to replace `// common rust`.

2021-09-07 21:16 UTC, jhumlick commented on common_rust/rdiff/rdiff.rs
> +fn split_string(line: String) -> Result<(String, String), &'static str> {
I have removed this function as it is no longer needed/used anywhere.

2021-09-23 22:36 UTC, closed without merging